import 'metro_station.dart';

class MetroData {
  static final MetroLine margHelwanLine = MetroLine(
    id: 'line_1',
    name: 'Marg - Helwan',
    stations: [
      MetroStation(
        id: 'helwan',
        name: 'Helwan',
        nameArabic: 'حلوان',
        latitude: 29.8489,
        longitude: 31.3342,
        lineId: 'line_1',
        order: 1,
      ),
      MetroStation(
        id: 'ain_helwan',
        name: 'Ain Helwan',
        nameArabic: 'عين حلوان',
        latitude: 29.8627,
        longitude: 31.3248,
        lineId: 'line_1',
        order: 2,
      ),
      MetroStation(
        id: 'helwan_university',
        name: 'Helwan University',
        nameArabic: 'جامعة حلوان',
        latitude: 29.8693,
        longitude: 31.3201,
        lineId: 'line_1',
        order: 3,
      ),
      MetroStation(
        id: 'wadi_hof',
        name: 'Wadi Hof',
        nameArabic: 'وادي حوف',
        latitude: 29.8792,
        longitude: 31.3138,
        lineId: 'line_1',
        order: 4,
      ),
      MetroStation(
        id: 'hadayek_helwan',
        name: 'Hadayek Helwan',
        nameArabic: 'حدائق حلوان',
        latitude: 29.8972,
        longitude: 31.3040,
        lineId: 'line_1',
        order: 5,
      ),
      MetroStation(
        id: 'el_maasara',
        name: 'El Maasara',
        nameArabic: 'المعصرة',
        latitude: 29.9061,
        longitude: 31.2995,
        lineId: 'line_1',
        order: 6,
      ),
      MetroStation(
        id: 'tora_el_asmant',
        name: 'Tora El Asmant',
        nameArabic: 'طرة الأسمنت',
        latitude: 29.9261,
        longitude: 31.2877,
        lineId: 'line_1',
        order: 7,
      ),
      MetroStation(
        id: 'kozzika',
        name: 'Kozzika',
        nameArabic: 'كوتسيكا',
        latitude: 29.9364,
        longitude: 31.2818,
        lineId: 'line_1',
        order: 8,
      ),
      MetroStation(
        id: 'tora_el_balad',
        name: 'Tora El Balad',
        nameArabic: 'طرة البلد',
        latitude: 29.9467,
        longitude: 31.2729,
        lineId: 'line_1',
        order: 9,
      ),
      MetroStation(
        id: 'sakanat_el_maadi',
        name: 'Sakanat El Maadi',
        nameArabic: 'ثكنات المعادي',
        latitude: 29.9531,
        longitude: 31.2631,
        lineId: 'line_1',
        order: 10,
      ),
      MetroStation(
        id: 'maadi',
        name: 'Maadi',
        nameArabic: 'المعادي',
        latitude: 29.9604,
        longitude: 31.2575,
        lineId: 'line_1',
        order: 11,
      ),
      MetroStation(
        id: 'hadayek_el_maadi',
        name: 'Hadayek El Maadi',
        nameArabic: 'حدائق المعادي',
        latitude: 29.9701,
        longitude: 31.2506,
        lineId: 'line_1',
        order: 12,
      ),
      MetroStation(
        id: 'dar_el_salam',
        name: 'Dar El Salam',
        nameArabic: 'دار السلام',
        latitude: 29.9820,
        longitude: 31.2421,
        lineId: 'line_1',
        order: 13,
      ),
      MetroStation(
        id: 'el_zahraa',
        name: 'El Zahraa',
        nameArabic: 'الزهراء',
        latitude: 29.9953,
        longitude: 31.2314,
        lineId: 'line_1',
        order: 14,
      ),
      MetroStation(
        id: 'mar_girgis',
        name: 'Mar Girgis',
        nameArabic: 'مار جرجس',
        latitude: 30.0061,
        longitude: 31.2297,
        lineId: 'line_1',
        order: 15,
      ),
      MetroStation(
        id: 'el_malek_el_saleh',
        name: 'El Malek El Saleh',
        nameArabic: 'الملك الصالح',
        latitude: 30.0175,
        longitude: 31.2312,
        lineId: 'line_1',
        order: 16,
      ),
      MetroStation(
        id: 'al_sayeda_zeinab',
        name: 'Al Sayeda Zeinab',
        nameArabic: 'السيدة زينب',
        latitude: 30.0294,
        longitude: 31.2354,
        lineId: 'line_1',
        order: 17,
      ),
      MetroStation(
        id: 'saad_zaghloul',
        name: 'Saad Zaghloul',
        nameArabic: 'سعد زغلول',
        latitude: 30.0372,
        longitude: 31.2384,
        lineId: 'line_1',
        order: 18,
      ),
      MetroStation(
        id: 'sadat',
        name: 'Sadat',
        nameArabic: 'السادات',
        latitude: 30.0444,
        longitude: 31.2346,
        lineId: 'line_1',
        order: 19,
      ),
      MetroStation(
        id: 'nasser',
        name: 'Nasser',
        nameArabic: 'جمال عبد الناصر',
        latitude: 30.0536,
        longitude: 31.2387,
        lineId: 'line_1',
        order: 20,
      ),
      MetroStation(
        id: 'orabi',
        name: 'Orabi',
        nameArabic: 'عرابي',
        latitude: 30.0570,
        longitude: 31.2422,
        lineId: 'line_1',
        order: 21,
      ),
      MetroStation(
        id: 'al_shohadaa',
        name: 'Al Shohadaa',
        nameArabic: 'الشهداء',
        latitude: 30.0610,
        longitude: 31.2460,
        lineId: 'line_1',
        order: 22,
      ),
      MetroStation(
        id: 'ghamra',
        name: 'Ghamra',
        nameArabic: 'غمرة',
        latitude: 30.0689,
        longitude: 31.2646,
        lineId: 'line_1',
        order: 23,
      ),
      MetroStation(
        id: 'el_demerdash',
        name: 'El Demerdash',
        nameArabic: 'الدمرداش',
        latitude: 30.0771,
        longitude: 31.2778,
        lineId: 'line_1',
        order: 24,
      ),
      MetroStation(
        id: 'manshiet_el_sadr',
        name: 'Manshiet El Sadr',
        nameArabic: 'منشية الصدر',
        latitude: 30.0819,
        longitude: 31.2875,
        lineId: 'line_1',
        order: 25,
      ),
      MetroStation(
        id: 'kobri_el_qobba',
        name: 'Kobri El Qobba',
        nameArabic: 'كوبري القبة',
        latitude: 30.0872,
        longitude: 31.2940,
        lineId: 'line_1',
        order: 26,
      ),
      MetroStation(
        id: 'hammamat_el_qobba',
        name: 'Hammamat El Qobba',
        nameArabic: 'حمامات القبة',
        latitude: 30.0910,
        longitude: 31.2991,
        lineId: 'line_1',
        order: 27,
      ),
      MetroStation(
        id: 'saray_el_qobba',
        name: 'Saray El Qobba',
        nameArabic: 'سراي القبة',
        latitude: 30.0978,
        longitude: 31.3043,
        lineId: 'line_1',
        order: 28,
      ),
      MetroStation(
        id: 'hadayeq_el_zaitoun',
        name: 'Hadayeq El Zaitoun',
        nameArabic: 'حدائق الزيتون',
        latitude: 30.1056,
        longitude: 31.3104,
        lineId: 'line_1',
        order: 29,
      ),
      MetroStation(
        id: 'helmeyet_el_zaitoun',
        name: 'Helmeyet El Zaitoun',
        nameArabic: 'حلمية الزيتون',
        latitude: 30.1133,
        longitude: 31.3140,
        lineId: 'line_1',
        order: 30,
      ),
      MetroStation(
        id: 'el_matareyya',
        name: 'El Matareyya',
        nameArabic: 'المطرية',
        latitude: 30.1211,
        longitude: 31.3138,
        lineId: 'line_1',
        order: 31,
      ),
      MetroStation(
        id: 'ain_shams',
        name: 'Ain Shams',
        nameArabic: 'عين شمس',
        latitude: 30.1311,
        longitude: 31.3190,
        lineId: 'line_1',
        order: 32,
      ),
      MetroStation(
        id: 'ezbet_el_nakhl',
        name: 'Ezbet El Nakhl',
        nameArabic: 'عزبة النخل',
        latitude: 30.1394,
        longitude: 31.3243,
        lineId: 'line_1',
        order: 33,
      ),
      MetroStation(
        id: 'el_marg',
        name: 'El Marg',
        nameArabic: 'المرج',
        latitude: 30.1521,
        longitude: 31.3358,
        lineId: 'line_1',
        order: 34,
      ),
      MetroStation(
        id: 'new_el_marg',
        name: 'New El Marg',
        nameArabic: 'المرج الجديدة',
        latitude: 30.1636,
        longitude: 31.3385,
        lineId: 'line_1',
        order: 35,
      ),
    ],
  );

  static List<MetroLine> get allLines => [margHelwanLine];

  static MetroLine? getLineById(String lineId) {
    try {
      return allLines.firstWhere((line) => line.id == lineId);
    } catch (_) {
      return null;
    }
  }
}